//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterpageTest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AssignmentEntities1 : DbContext
    {
        public AssignmentEntities1()
            : base("name=AssignmentEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MCQAssessment> MCQAssessments { get; set; }
        public virtual DbSet<MCQAssessmentList> MCQAssessmentLists { get; set; }
        public virtual DbSet<MCQQuestion> MCQQuestions { get; set; }
        public virtual DbSet<MCQResponse> MCQResponses { get; set; }
        public virtual DbSet<MCQResult> MCQResults { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<WrittenAssessment> WrittenAssessments { get; set; }
        public virtual DbSet<WrittenAssessmentList> WrittenAssessmentLists { get; set; }
        public virtual DbSet<WrittenQuestion> WrittenQuestions { get; set; }
        public virtual DbSet<WrittenResponse> WrittenResponses { get; set; }
        public virtual DbSet<WrittenResult> WrittenResults { get; set; }
    }
}
