//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterpageTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WrittenQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WrittenQuestion()
        {
            this.WrittenResponses = new HashSet<WrittenResponse>();
        }
    
        public int WrittenQuestionID { get; set; }
        public string QuestionTitle { get; set; }
        public Nullable<int> WrittenID { get; set; }
        public Nullable<int> MaximumScore { get; set; }
    
        public virtual WrittenAssessment WrittenAssessment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WrittenResponse> WrittenResponses { get; set; }
    }
}
